meteor:
  image: ulexus/meteor
  ports:
    - "3000:80"
  links:
    - mongo
  environment:
    - MONGO_URL=mongodb://mongo/ctbd
    - ROOT_URL=http://www.cleanthebayday.net
    - MAIL_URL=smtp://some.mailserver.com:25
    - VIRTUAL_HOST=www.cleanthebayday.net
    - REPO=https://github.com/Code4HR/cbf-clean
  restart: always
mongo:
  image: tutum/mongodb
  expose:
    - "27017"
    - "28017"
  environment:
    - AUTH=no
  volumes:
    - "/var/cbf-clean:/data/db"
  mem_limit: 200m
  restart: always
