// on each server startup add an array in memory for all the partners

Meteor.startup(
  function () {
  // code to run on server at startup
  // if (Partners.find().count() === 0) {
    Partners.remove({});
    var names = [
    "Anheuser-Busch/James City County",
    "Chesterfield County",
    "City of Charlottesville - RCS, TNC, VMN",
    "City of Chesapeake",
    "City of Hampton",
    "City of Manassas",
    "City of Newport News",
    "City of Norfolk (Keep Norfolk Beautiful)",
    "City of Poquoson",
    "City of Portsmouth",
    "City of Suffolk",
    "City of Virginia Beach",
    "Clean Virginia Waterways",
    "County of York",
    "Crown Pointe Marina",
    "HRSD Employees Association",
    "James City County",
    "James River Park System",
    "Navy - JEB Fort Story",
    "Navy - JEB Little Creek",
    "Navy - Lafayette River Annex",
    "Navy - NAS Oceana/NAS Oceana Dam Neck Annex",
    "Navy - NAS Patuxent River, MD",
    "Navy - Naval Medical Center Portsmouth",
    "Navy - Naval Station Norfolk (NSN)",
    "Navy - New Kent ROTHR Site",
    "Navy - Norfolk Naval Shipyard",
    "Navy - NSA Norfolk",
    "Navy - NWS Yorktown",
    "Navy CTBD Regional Coordinator",
    "Port of Virginia",
    "Reston Association",
    "Smithfield Packing Co.",
    "SouthEast Expeditions (Onancock Creek)",
    "State Park - Bear Creek Lake SP",
    "State Park - Belle Isle SP",
    "State Park - Caledon SP",
    "State Park - Chippokes Plantation SP",
    "State Park - Douthat SP",
    "State Park - False Cape SP",
    "State Park - High Bridge Trail SP",
    "State Park - Holliday Lake SP",
    "State Park - James River SP",
    "State Park - Kiptopeke SP",
    "State Park - Lake Anna SP",
    "State Park - Leesylvania SP",
    "State Park - Mason Neck SP",
    "State Park - Pocahontas SP",
    "State Park - Powhatan SP",
    "State Park - Sailors Creek SP",
    "State Park - Shenandoah River SP",
    "State Park - Sky Meadows SP",
    "State Park - Twin Lakes SP",
    "State Park - Westmoreland SP",
    "State Park - York River SP",
    "Tangier Pride, Inc.",
    "US Army Corps of Engineers (Craney Island)",
    "Vinings Marine Group (Willoughby Harbor Marina)",
    "Virginia Eastern Shore Land Trust",
    "OTHER - Be specific in next field"];
    for (var i = 0; i < names.length; i++)
      Partners.insert({name: names[i]});

});
